name: Explodr
main: com.omfgp.explodr.Main
commands:
  Explodr:
    description: Explodes things all around you.
    usage: /<command>
  Findr:
    description: Shows your location on the screen.
    usage: /<command>
  Testr:
    description: Shows arguments passed to Testr.
    usage: /<command>
  Drillr:
    description: Drills down deep with explosions!
    usage: /<command>
  Flamr:
    description: Casts the classic fs explo combo on target.
    usage: /<command>
version: 0.0.1